#complementary strands
s = "ACACAATCCTATGGGCCACTGACTAATGAATATTTCTTCCCGAGCGACCAAGTGCCGACCGGGGCCGGGCGGGGACAACAAACTACCAGAGCGGAGCACAGCAGGCACGATTCAACCCGCGTCGGGAGCTGTAATCGTCACCGATTCTCGAACGCCCCAGGAGTTTTTGCTTTAGCCGTTCGCCGAAATAGATGTATAGCTACGCCGCCTACTATCAACCCTAGCCTTTGCAAGCGGCCCGTTCCTCATACAACGTAGTGTACTTATTGACTCGTGAGCTATGAGTGTTCACTAGCTGTTGCTGCCTGAGCGGAAACTATCTCGCAACTGGAGCTAAAACTCATATGCGGTCTTTGAACGATACAGTACTTCCCCATACGAAACGTTGTTCTGAGTGTCACGAGGTATTTGGAACTCTTGACTCAGGTTAAAGCGCAGCATCGCTCCCGGACCACTGTAGGGCCTATACCCGAAGGCCACTAATAATCTACTACAGGATCATCGATTGGCTTGATCCTAGATGACGTTGAAACACGTAGATTAATCCCCTGGATTATATCAACGCCACTTCCTAATCCTGCCGCTTTACGAGATTGCCTCTAGTTCCCTCAATCGGGCGTTTGAGTGGTGTTAGCCGTGCTGATACGACCCGAGCGCCCCTAGCAAGGATAATTTGGACTGGAGCTTATGACAGCGCCCTATTAACGTTAAACAAGAGTCTTATAGTGACCAATTCCGCGAGCTCCGGGGTGAAATGATTTGTTATACCACGCCGGCATCTCTCTCGTCTCACTATTGCGTCCTGTATTTTTAAAGCTGAGTTAATCTTAATTATAGTTGTCATGGTACAACGGCGACTTGCCCAACATTTCCAAGAAATGGCGTCAGGCGTAGGGTCTGTCTCCGACACATTTATCTGTCCCCGCTCCCGCCTAAGCCTTAAGGCATTGTGAAGCTATTGACATAGAAACACTACAGAGCG"
out = ""
for letter in s:
    if letter == "A":
        out += "T"
    if letter == "C":
        out += "G"
    if letter == "G":
        out += "C"
    if letter == "T":
        out += "A"
i = len(out) - 1
while i >= 0:
    print(out[i], end = '')
    i -= 1
print()