#inferring mRNA from protein
#given an amino acid string s 
#output total number of RNA strings that could have been used % 1,000,000
#!remember STOP codon +3
#hint mod 10, 100, 1000 is just removing those digits 23 mod 10 -> 3|| 4333 mod 100 -> 33
codon_possiblility_count = {
"F":2,
"L":6,
"S":6,
"Y":2,
"C":2,
"W":1,
"P":4,
"H":2,
"Q":2,
"R":6,
"I":3,
"M":1,
"T":4,
"N":2,
"K":2,
"V":4,
"A":4,
"D":2,
"E":2,
"G":4,
}
s = "MSGEYWCTERCSVDEQVFNMKVQRCIHTWWDVGYMDMNHHFPSQLESIRYICRYESFCYDDNFCCNPTFFKSGWYAETWADLQSIPLRGTFVTNYPTCVLHPPYGLQFLIQPWAPDLTSFVYLQHSPTWRFTGIGADNDTRICVMDYQLGTRHEQNTAYACYFYVKEQKYLDHWVYSMHQYMSHGTIKIVSRIQKRKCLAINREHQGKKPSFYIYQHSRGKFISKCKWAVADGTTKNLWYSNGGRYNNYVELFKHKIIIRPHWNLFPWPFPMTSRMQIHSSLSFCRWVWMHRCPGVNPFKPVYKWMGLAIRCNLLNTWRQKFWDGGGAWLVAITSNEKHLFDALHEIGIDPRTMRDWDAHFLCIVCRSYGHVWTKWRRIARNYDTGDGRVKHGNKPSYFSCTPVGAHVRVDAQALEACAKFYYVVTARMQQMDQTNHRLDCLPLILVVPTKKGCDFPSKRKSYHKLQNMPIQMVMAVSTILYHDLMNKFSSLILCRMCPFLQFTRMEQMIQEDSSAPRCYGKHTFWVWKDFGSKEERGTISVTPWENVICGFATSINHVMCEQAHHPKWHWQNWRDKQFSSSKFLLSMQSQECECHDEWFRNTQEMTRYMAEGNFCENELSRLKEVSQVWQWGRLKRNGWQCDIHQQGHEVDYEYYVIIRANMYCQNHCYHAYLRFKKPFAFIVSLMVVMYYVKKIFQETKWPMERHVIYMRLRWVDEFIQSNKVCGQRSMNKIERWPAANAIWMQFKWAAAMINGREVRSEPWFVDKKEKQNFMGENAMENPQPQMCCWQSWFKPPKGQLHMQQGQGPAGKVYLNQAERDHQEVLFPQRYGLCSMIRGCSFKTFKCCDRGICWEMSMYRNVFWCVRVDNDKGDMPEWAHHVVLFRKQFQKMAQLSSQWEIGKMEFTDWEIPAPVHQSLFKCMIMALHFRNYATMYSTEYKDEEPDSAFPKGPQTPSNYYLDDKSCWTWCMQYSYITSLCNIGFKHNNPAQFMLMMWQD"
#check if string contains Stop, then go through each letter up to that position
#look up # of options in dictionary and add to total +3 for Stop
total = 1
for letter in s:
    total = total * codon_possiblility_count.get(letter)
    total = total % 1000000
total = total * 3
total = total % 1000000
print(total)