#find substrings
s = "ACGGCGGTACGGCGGAACGGCGGGAACGGCGGTAACGGCGGCTTCGGCTACACGGCGGACGGCGGGCTGGAATCCCACGGCGGACGGCGGACGGCGGGCGACGGCGGTGGTCTACGGCGGACGGCGGTACGGCGGGACGGCGGACACGGCGGGGACGGCGGAAGACGGCGGACGGCGGACGGCGGAACACGGCGGACACGGCGGTCTACGGCGGGGCCACGGCGGACGGCGGGTGCAACGGCGGGACGGCGGAACACGGCGGTGTCACGGCGGGGCACGGCGGGTTACGGCGGCAAACGGCGGTTTGTATACGGCGGCCCACGGCGGTAACGGCGGAACGGCGGGAACGGCGGGATACGGCGGACTACGGCGGACGGCGGCACGGCGGTACGGCGGTACGGCGGGCCACAACGGCGGACGGCGGACGGCGGGACGGCGGAAATGTCACGGCGGCACGGCGGGACGGCGGAACGGCGGCACGGCGGAGCGATACGGCGGCGGGTACGGCGGACGGCGGACGGCGGGTTCCACGGCGGTAAACGGCGGACGGCGGAACTGCACACGGCGGACGGCGGCTGACGGCGGCAACGGCGGACGGCGGACGGCGGACGGCGGCAACGGCGGGACGGCGGGACGGCGGACGGCGGACGGCGGACGGCGGAACGGCGGTACGGCGGACGGCGGACGGCGGCGTACGGCGGAGGACGGCGGGAGACGGCGGACGGCGGTCTTTGAACGGCGGAGAGCGTACGGCGGACGGCGGCGAACAACGGCGGACGGCGGTTATACGGCGGACGGCGGAACGGCGGTTTGACGGCGGTTCGACGGCGGACGGCGGACGGCGGACGGCGGAAGTGACGGCGGCACGGCGGTTCTACGGCGGAACGGCGGTGACGGCGGACGGCGGACCCACGGCGGGACGGCGGGAACACGGCGGCATACGGCGGGCACGGCGG"
t = "ACGGCGGAC"
c = 1
for count, letter in enumerate(s):
    #count+1 because Rosalind wants 1 indexed for some stupid reason
    if letter == t[0]:
        if((count + len(t)) <= len(s)):
            for i in range (count + 1, (count + len(t))):
                if t[c] == s[i]:
                    c+=1
                else:
                    c = 1
                    break
                if c == len(t):
                    print(count+1, end = " ")
                    c = 1
print()